services:
  web:
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL:-dummy_db_url}
        CLERK_SECRET_KEY: ${CLERK_SECRET_KEY:-dummy_clerk_secret}
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:-dummy_publishable}
        NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY: ${NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY:-dummy_ik_public}
        IMAGEKIT_PRIVATE_KEY: ${IMAGEKIT_PRIVATE_KEY:-dummy_ik_private}
        NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT: ${NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT:-https://example.com}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
    env_file:
      - .env        # <-- real secrets for the running container
    ports:
      - "3000:3000"
